# Generated by Django 5.0 on 2023-12-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Link',
            new_name='Links',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='click',
            new_name='clicks',
        ),
    ]
