# Generated by Django 3.2.1 on 2024-01-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='isdeletable',
            field=models.BooleanField(default=1),
        ),
    ]
